package placeholder

import (
	"bytes"
	"image/png"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGenerate_ReturnsValidSquarePNG(t *testing.T) {
	sizes := []int{1, 50, 200}

	for _, size := range sizes {
		data, err := Generate(size)
		require.NoError(t, err)
		require.NotEmpty(t, data)

		img, err := png.Decode(bytes.NewReader(data))
		require.NoError(t, err, "generated bytes must be a valid PNG")

		bounds := img.Bounds()
		require.Equal(t, size, bounds.Dx())
		require.Equal(t, size, bounds.Dy())
	}
}
